---
title: "Lecture 7: Joint Distribution"
output: 
  learnr::tutorial:
    css: css/styles.css
runtime: shiny_prerendered
---


```{r setup, include=FALSE}
library(learnr)
library(tidyverse)
library(ggplot2)
```


## Simulating Joint Distributions

Suppose $R$ and $\theta$ are two continuous random variables with the following distributions.

$$R\sim\text{U}(0, 1)\quad\text{and}\quad\theta\sim\text{U}(0, \pi)$$

Let $X=R\cos(\theta)$ and $Y=R\sin(\theta)$. Simulate 100,000 pairs of $(X,Y)$.


```{r simulatej, exercise=TRUE, exercise.lines=15}

```

### Plotting Simulated Values

The following code plots a semi circle with radius 1. Add the simulated points $(x_i,y_i)$ for $i=1,\dots,1000$ on to the plot.

```{r plotbase, exercise=TRUE, fig.asp=2/3, exercise.lines=25}
circlei <- seq(0, pi, 0.01)
plot(cos(circlei), sin(circlei), type = "l",
     xlab = "x", ylab = "y")
```


Alternatively, in `ggplot`...

```{r plotgg, exercise=TRUE, fig.asp=2/3, exercise.lines=25}
ggplot() +
  theme_classic() +
  geom_line(aes(x = cos(circlei), y = sin(circlei))) +
  labs(x = "x", y = "y")
```

